PhotoContest/PhotoContest.Web/Models/PhotoViewModels/PhotoViewModel.cs
using PhotoContest.Data.Models;
using PhotoContest.Services.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoContest.Web.Models.PhotoViewModels
{
    public class PhotoViewModel
    {
        public PhotoViewModel(PhotoDTO photo)
        {
            this.Id = photo.Id;
            this.Title = photo.Title;
            this.Description = photo.Description;
            this.PhotoUrl = photo.PhotoUrl;
            this.User = photo.User;
            this.Contest = photo.Contest;
            this.Category = photo.Category;
            this.Points = photo.Points;
        }
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        [Display(Name ="Picture")]
        public string PhotoUrl { get; set; }
        public string User { get; set; }
        public string Contest { get; set; }
        public string ContestStatus { get; set; }
        public string Category { get; set; }
        public double Points { get; set; }
        public List<JuryMember> Juries { get; set; } = new List<JuryMember>();
        public List<Review> Reviews { get; set; } = new List<Review>();
    }
}

PhotoContest/PhotoContest.Web/Controllers/ContestsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;
using PhotoContest.Data;
using PhotoContest.Services.Contracts;
using PhotoContest.Services.Models;
using PhotoContest.Services.Models.Create;
using PhotoContest.Services.Models.Update;
using PhotoContest.Services.Services;
using PhotoContest.Web.Models.ContestViewModels;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoContest.Web.Controllers
{
    public class ContestsController : Controller
    {
        private readonly PhotoContestContext _context;
        private readonly IContestService contestService;
        private readonly ICategoryService categoryService;
        private readonly SignInManager<User> signInManager;
        private readonly IUserContestService userContestService;
        private readonly IPhotoService photoService;
        private readonly IUserService userService;
        private readonly IToastNotification toastNotification;

        public ContestsController(PhotoContestContext context,
                                  IContestService contestService,
                                  ICategoryService categoryService,
                                  SignInManager<User> signInManager,
                                  IUserContestService userContestService,
                                  IPhotoService photoService,
                                  IUserService userService,
                                  IToastNotification toastNotification)
        {
            _context = context;
            this.contestService = contestService;
            this.categoryService = categoryService;
            this.signInManager = signInManager;
            this.userContestService = userContestService;
            this.photoService = photoService;
            this.userService = userService;
            this.toastNotification = toastNotification;
        }

        /// <summary>
        /// Get all contests
        /// </summary>
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var contests = await this.contestService.GetAllAsync();
            if (User.IsInRole("User"))
            {
                return RedirectToAction("AllOpen");
            }
            else
                return View(contests.Select(c => new ContetsViewModel(c)));
        }

        /// <summary>
        /// Get all open contests
        /// </summary>
        /// <returns>Return a list with all open contests</returns>
        [Authorize]
        public async Task<IActionResult> AllOpen()
        {
            var contests = await this.contestService.AllOpenViewAsync();
            var userContests = await this.userContestService.GetAllUserContestsAsync();
            var photos = await this.photoService.GetAllAsync();
            var juries = await this.contestService.GetAllJuriesAsync();
            return View(contests.Select(c => new ContetsViewModel(c) { AllUserContests = userContests, AllPhotos = photos.ToList(), Juries = juries.ToList() }));
        }

        /// <summary>
        /// Filter all open contests
        /// </summary>
        /// <param name="status">Phase of the contests to filter by</param>
        /// <returns>A list of all open contests after filtering</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> GetOpenFiltered(string status)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var contests = await this.contestService.GetAllOpenAsync(status);
                    var userContests = await this.userContestService.GetAllUserContestsAsync();
                    var photos = await this.photoService.GetAllAsync();
                    var juries = await this.contestService.GetAllJuriesAsync();
                    return View(contests.Select(c => new ContetsViewModel(c) { AllUserContests = userContests, AllPhotos = photos.ToList(), Juries = juries.ToList() }));
                }
                catch (Exception e)
                {
                    toastNotification.AddErrorToastMessage(e.Message, new NotyOptions());
                    var path = Request.Path.Value.ToString() + status;
                    return Redirect(path);
                }
            }
            return View();
        }

        /// <summary>
        /// Get details of a contest
        /// </summary>
        /// <param name="name">Name of the contest</param>
        [Authorize]
        public async Task<IActionResult> Details(string name)
        {
            var contest = await this.contestService.FindContestByNameAsync(name);
            var userContests = await this.userContestService.GetAllUserContestsAsync();
            var photos = await this.photoService.GetAllAsync();
            var juries = await this.contestService.GetAllJuriesAsync();
            var contestDTO = new ContestDTO(contest);
            return View(new ContetsViewModel(contestDTO) { AllUserContests = userContests, AllPhotos = photos.ToList(), Juries = juries.ToList() });
        }

        /// <summary>
        /// Show a for to create a contest
        /// </summary>
        [Authorize(Roles = "Admin, Organizer")]
        public async Task<IActionResult> Create()
        {
            var categories = await this.categoryService.GetAllBaseAsync();
            ViewData["Categories"] = new SelectList(categories, "Name", "Name");
            return View();
        }

        /// <summary>
        /// Create a contest
        /// </summary>
        /// <param name="createViewModel">Details of the contest to create</param>
        /// <returns>To list of all contests if successful or go to error page for bad request</returns>
        [Authorize(Roles = "Admin, Organizer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateContestViewModel createViewModel)
        {
            var newContestDTO = new NewContestDTO()
            {
                Name = createViewModel.Name,
                CategoryName = createViewModel.CategoryName,
                IsOpen = createViewModel.IsOpen,
                Phase1 = createViewModel.Phase1,
                Phase2 = createViewModel.Phase2,
                Finished = createViewModel.Finished
            };

            if (ModelState.IsValid)
            {
                try
                {
                    await this.contestService.CreateAsync(newContestDTO);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    toastNotification.AddErrorToastMessage(e.Message, new NotyOptions());
                    return Redirect(Request.Path.Value.ToString());
                }
            }
            var categories = await this.categoryService.GetAllBaseAsync();
            ViewData["Categories"] = new SelectList(categories, "Name", "Name");
            return View();
        }

        /// <summary>
        /// Show for to edit a contest
        /// </summary>
        /// <param name="name">Name of the contest to edit</param>
        [Authorize(Roles = "Admin, Organizer")]
        public async Task<IActionResult> Edit(string name)
        {
            var contest = await this.contestService.FindContestByNameAsync(name);
            var updateContestDTO = new EditContestViewModel();

            updateContestDTO.Name = contest.Name;
            updateContestDTO.Category = contest.Category.Name;
            updateContestDTO.IsContestOpen = contest.IsOpen;
            updateContestDTO.Phase1 = contest.Phase1.ToString("dd.MM.yy HH:mm");
            updateContestDTO.Phase2 = contest.Phase2.ToString("dd.MM.yy HH:mm");
            updateContestDTO.Finished = contest.Finished.ToString("dd.MM.yy HH:mm");

            var categories = await this.categoryService.GetAllBaseAsync();
            ViewData["Categories"] = new SelectList(categories, "Name", "Name");
            return View(updateContestDTO);
        }

        /// <summary>
        /// Edit a contest
        /// </summary>
        /// <param name="name">Name of the contest to edit</param>
        /// <param name="editViewModel">Details to edit</param>
        /// <returns>To list of all contests if successful or go to error page for bad request</returns>
        [Authorize(Roles = "Admin, Organizer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string name, EditContestViewModel editViewModel)
        {
           
            if (ModelState.IsValid)
            {
                try
                {
                    var updateContestDTO = new UpdateContestDTO();
                    updateContestDTO.CategoryName = editViewModel.Category;
                    updateContestDTO.IsOpen = editViewModel.IsContestOpen;
                    updateContestDTO.Phase1 = editViewModel.Phase1;
                    updateContestDTO.Phase2 = editViewModel.Phase2;
                    updateContestDTO.Finished = editViewModel.Finished;
                    await this.contestService.UpdateAsync(name, updateContestDTO);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    toastNotification.AddErrorToastMessage(e.Message, new NotyOptions());
                    var path = Request.Path.Value.ToString() + "?name=" + editViewModel.Name;
                    return Redirect(path);
                }
            }
            var categories = await this.categoryService.GetAllBaseAsync();
            ViewData["Categories"] = new SelectList(categories, "Name", "Name");
            return View();
        }

        /// <summary>
        /// Get a contest to delete
        /// </summary>

PhotoContest/PhotoContest.Web/Views/Photos/Create.cshtml
@model CreatePhotoViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Upload photo</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ContestName" />
            <div class="form-group">
                <label asp-for="ContestName " class="control-label"></label> @Html.DisplayFor(model => model.ContestName)
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input asp-for="File" accept="image/*" />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
            <div class="alert alert-danger">
                <strong>Warning!</strong> Data cannot be changed later!
            </div>
            <div class="form-group">
                <input type="submit" value="Upload" class="btn btn-outline-success" />
                <a class="btn btn-outline-dark" onclick="history.go(-1);">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PhotoContest/PhotoContest.Web/Views/Photos/Delete.cshtml
@model PhotoViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete photo</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhotoUrl)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.PhotoUrl" width="200" height="200" asp-append-version="true" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contest)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contest)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Points)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Points)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a class="btn btn-outline-dark" onclick="history.go(-1);">Back</a>
    </form>
</div>

PhotoContest/PhotoContest.Web/Views/Photos/Edit.cshtml
@model EditPhotoViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Update photo details</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a class="btn btn-dark" onclick="history.go(-1);">Back</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PhotoContest/PhotoContest.Web/Views/Photos/GetContestsPhotos.cshtml
@model IEnumerable<PhotoViewModel>
@inject SignInManager<User> signInManager
@{
    ViewData["Title"] = "GetContestsPhotos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Contest's photos</h2>
@if (Model.Count() == 0)
{
    <h3>There are no photos for this contest</h3>
}
else
{
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <partial name="_SinglePhotoPartial" model="item" />
            }
        </div>
    </div>
}
<br />
<div>
    <a class="btn btn-outline-dark" asp-action="Index" asp-controller="Contests">All contests</a>
</div>

PhotoContest/PhotoContest.Web/Views/Photos/GetPhotosForUser.cshtml
@model IEnumerable<PhotoViewModel>
@inject SignInManager<User> SignInManager
@{
    ViewData["Title"] = "GetPhotosForUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>My photos</h2>
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <partial name="_SinglePhotoPartial" model="item" />
        }
    </div>
</div>
<br />
<a class="btn btn-outline-dark" onclick="history.go(-1);">Back</a>

PhotoContest/PhotoContest.Web/Views/Photos/Index.cshtml
@model IEnumerable<PhotoViewModel>
@inject SignInManager<User> SignInManager
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All photos</h2>

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <partial name="_SinglePhotoPartial" model="item" />
        }
    </div>
</div>
<br />
<a class="btn btn-outline-dark" onclick="history.go(-1);">Back</a>